name: 'Install POCL Dependencies'
description: 'Installs dependencies needed to build and run POCL'
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        export LLVM_VERSION=20
        sudo apt-get install -y \
          python3-dev libpython3-dev build-essential ocl-icd-libopencl1 \
          cmake git pkg-config libclang-${LLVM_VERSION}-dev clang-${LLVM_VERSION} \
          llvm-${LLVM_VERSION} make ninja-build ocl-icd-libopencl1 ocl-icd-dev \
          ocl-icd-opencl-dev libhwloc-dev zlib1g zlib1g-dev clinfo dialog apt-utils \
          libxml2-dev libclang-cpp${LLVM_VERSION}-dev libclang-cpp${LLVM_VERSION} \
          llvm-${LLVM_VERSION}-dev
